name: Test Zola Installation

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
          file zola.tar.gz
          tar xzvf zola.tar.gz -C /usr/local/bin
          zola --version

      - name: Build Site
        run: zola build