name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
          tar -xzvf zola.tar.gz -C /usr/local/bin
          zola --version

      - name: Build site
        run: zola build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zola-site
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: zola-site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2