name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/latest/download/zola-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin
          
      - name: Verify Zola installation
        run: zola --version

      - name: Build site
        run: zola build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zola-site
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging before deploy
        run: |
          echo "Checking Git status"
          git status
          echo "Listing git remotes"
          git remote -v
          echo "Listing branches"
          git branch -a
          echo "Listing all files"
          ls -la

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2